
# >>> coursier install directory >>>
export PATH="$PATH:/home/yamada/.local/share/coursier/bin"
# <<< coursier install directory <<<


# Added by Toolbox App
export PATH="$PATH:/home/yamada/.local/share/JetBrains/Toolbox/scripts"

# Load .bashrc
if [[ -f ~/.bashrc ]] ; then
     . ~/.bashrc
fi

# Locale
export LANG=ja_JP.UTF-8
export LC_TIME=ja_JP.UTF-8
